env:
  node: true
  es2021: true
  parser: "@typescript-eslint/parser"
extends: standard-with-typescript
plugins:
  - "@typescript-eslint"
overrides: []
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
rules:
  "@typescript-eslint/no-unused-vars":
    - warn
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"
      destructuredArrayIgnorePattern: "^_"
